spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/miniautorizador
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: mongo
      port: 27017
      username: user
      password: password
      database: miniautorizador
