springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  redis:
    host: localhost
    port: 6379
    time-life: 60
  datasource:
    url: jdbc:mysql://localhost:3307/miniautorizador
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: miniautorizador
